command: generate-dataset
engine_path: /scratch/gpfs/GRIFFITHS/ysagiv/tools/lc0/build/release/lc0
weights_path: /scratch/gpfs/GRIFFITHS/ysagiv/chess/weights/t1-256x10-distilled-swa-2432500.pb.gz
fens: /scratch/gpfs/GRIFFITHS/hl4291/tmp/human_fens_10k.txt
output_dir: /scratch/gpfs/GRIFFITHS/hl4291/tmp/human_trees_10k
search_budget: 96
min_nodes: 96
max_nodes: 96
seed: 42
multipv: 8
max_depth: 4
resume: true
start_index: 1500
end_index: 2000
