"""Registers headline statistics under a stable key, dumped to one .tex file of
``\\pgfkeyssetvalue`` macros so reports can cite the number and trace it back."""

from __future__ import annotations

_VALUES: dict[str, str] = {}


def pgf_set(key: str, value, fmt: str = "{:.4g}") -> str:
    """Register ``key -> value`` (formatted with ``fmt``, or used as-is if already a
    str) for the .tex export, and return the formatted string — so a call site can
    both print/plot a number and register it in one line, with no risk of the two
    drifting apart:

        s = pgf_set("board/rt/mean_s", np.exp(mean), "{:.1f}")
        ax.axvline(..., label=f"Mean = {s}s")
    """
    s = value if isinstance(value, str) else fmt.format(value)
    _VALUES[key] = s
    return s


def write_pgf_tex(path: str) -> None:
    """Dump every value registered so far (this process) to one .tex file of
    ``\\pgfkeyssetvalue{key}{value}`` lines, sorted by key for a stable diff."""
    import os
    lines = [
        r"% Auto-generated by src/analysis/board.py -- do not hand-edit.",
        r"% \usepackage{pgfkeys} then \pgfkeysvalueof{/key/path} to cite a value.",
    ]
    for key, value in sorted(_VALUES.items()):
        lines.append(f"\\pgfkeyssetvalue{{{key}}}{{{value}}}")
    out_dir = os.path.dirname(path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Saved pgf values: {path} ({len(_VALUES)} keys)")
